services:
  opencam-studio:
    build:
      context: .
      dockerfile: server/Dockerfile.allinone
    ports:
      - "3000:80"
    restart: unless-stopped
    volumes:
      - videos:/videos
      - proxies:/proxies
      - projects:/projects
      - output:/output
      - recordings:/recordings
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  videos:
  proxies:
  projects:
  output:
  recordings:
